#! /bin/sh

if (test $# -lt 2)
then
   db2 connect to sample
elif (test $# -lt 3)
then
   db2 connect to $2
else
   db2 connect to $2 user $3 using $4
fi

# Precompile the program.
if [ -f $1".sqc" ]
then
  db2 prep $1.sqc bindfile using ${1}L.bnd
  #db2 prep $1.sqc bindfile using ${1}L.bnd package using ${1}L sqlerror continue validate run
  if [ -f utilemb.sqc ]
  then
    db2 prep utilemb.sqc bindfile using utilembL.bnd package using utilembL
  fi
elif [ -f $1".sqC" ]
then
  db2 prep $1.sqC bindfile
  if [ -f utilemb.sqC ]
  then
   db2 prep utilemb.sqC
  fi
elif [ -f $1".sqb" ]
then
  db2 prep $1.sqb bindfile target mfcob CALL_RESOLUTION DEFERRED
fi

# Bind the program to the database.
db2 bind ${1}L.bnd blocking all validate run
db2 bind utilembL.bnd

# Disconnect from the database.
db2 connect reset
db2 terminate
